# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 01:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180624_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 1, 48, 10, 604334, tzinfo=utc)),
        ),
    ]
