# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_four_six_toefl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_six',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_toefl',
            field=models.IntegerField(default=0),
        ),
    ]
