# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180624_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='test_sin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='test_toefl',
            field=models.IntegerField(default=0),
        ),
    ]
