# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180624_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_sin',
            new_name='test_six',
        ),
    ]
