# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180624_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='review_six',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='review_toefl',
            field=models.IntegerField(default=0),
        ),
    ]
