# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180624_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='four',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='six',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toefl',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
    ]
