# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180624_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabularysnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('vocabularys', models.CharField(max_length=100)),
                ('paraphrases', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
