# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180626_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='already_in',
        ),
    ]
