# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180626_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='note_number',
            field=models.IntegerField(default=0),
        ),
    ]
