# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180626_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_number',
            field=models.IntegerField(default=0),
        ),
    ]
